# -*- coding: utf-8 -*-
"""
/***************************************************************************
 population_model
                                 A QGIS plugin
 The plugin offers diverse options of loss function and deep learning models to be applied on LandScan population rasters of custom AOI and time frame.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-17
        copyright            : (C) 2026 by Daksh17440
        email                : draciel.mart007@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load population_model class from file population_model.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .population_model import population_model
    return population_model(iface)
